# Stage 1: Build the frontend
FROM node:20-alpine AS frontend_builder

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend ./

RUN npm run build

# Stage 2: Fullstack Image
FROM node:20-alpine

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend ./

COPY --from=frontend_builder /app/dist ./public

CMD ["node", "server.js"]
