apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuber
  template:
    metadata:
      labels:
        app: kuber
    spec:
      containers:
      - name: kuber-container
        image: kuber:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"