apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuber-ingress
  labels:
    app.kubernetes.io/name: kuber-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kuber-service
            port: 
              number: 80
